name: Execute destroy terraform workspace on TF Cloud

on:
  workflow_dispatch:
    inputs:
      port_payload:
        required: true
        description: "Port's payload, including details for who triggered the action and general context (blueprint, run id, etc...)"
        type: string
    secrets: 
      PORT_CLIENT_ID: 
        required: true
      PORT_CLIENT_SECRET: 
        required: true
      TF_CLOUD_TOKEN: 
        required: true
      TF_CLOUD_TEAM_TOKEN: 
        required: true
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
     - name: get_workspace_id
       id: get_workspace_id
       run: |
         echo "::set-output name=id::$(curl 'https://app.terraform.io/api/v2/organizations/example-org-27d3a7/workspaces/${{ fromJson(inputs.port_payload).context.entity }}' -H 'content-type: application/vnd.api+json' -H 'Authorization: Bearer ${{ secrets.TF_CLOUD_TOKEN }}' | jq '.data.id')"
     - name: destroy
       run: |
        echo "Destroying workspace ${{ steps.get_workspace_id.outputs.id }}"
        curl 'https://app.terraform.io/api/v2/runs' \
          -H 'Content-Type: application/vnd.api+json' \
          -H 'Authorization: Bearer ${{ secrets.TF_CLOUD_TEAM_TOKEN }}' \
          --request POST \
          --data '{
              "data": {
                "attributes": {
                  "comment": "plan -destroy",
                  "is-destroy": true,
                  "refresh": true,
                  "refresh-only": false
                },
                "relationships": {
                  "workspace": {
                    "data": {
                      "type": "workspaces",
                      "id": ${{ steps.get_workspace_id.outputs.id }}
                    }
                  }
                },
                "type": "runs"
              }
            }'
                