name: Execute terraform module on TF Cloud

on:
  workflow_dispatch:
    inputs:
      port_payload:
        required: true
        description: "Port's payload, including details for who triggered the action and general context (blueprint, run id, etc...)"
        type: string
    secrets: 
      PORT_CLIENT_ID: 
        required: true
      PORT_CLIENT_SECRET: 
        required: true
      TF_CLOUD_TOKEN: 
        required: true
      TF_CLOUD_TEAM_TOKEN: 
        required: true
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
     - name: Get workspace id
       id: get_workspace_id
       run: |
         echo "::setoutput name=id::$(curl 'https://app.terraform.io/api/v2/organizations/example-org-27d3a7/workspace/${{ fromJson(inputs.port_payload).context.runId }}' \
          -H 'content-type: application/vnd.api+json' \
          -H 'Authorization: Bearer ${{ secrets.TF_CLOUD_TOKEN }}' | jq -r '.data.id')
     - name: destroy
       run: |
        curl 'https://app.terraform.io/api/v2/runs' \
          -H 'content-type: application/vnd.api+json' \
          -H 'Authorization: Bearer ${{ secrets.TF_CLOUD_TOKEN }}' \
          --data-raw '{"data":{"attributes":{"comment":"plan -destroy","is-destroy":true,"refresh":true,"refresh-only":false},"relationships":{"workspace":{"data":{"type":"workspaces","id":"${{ steps.get_workspace_id.id }}"}}},"type":"runs"}}' \
          --compressed
                