name: Execute terraform module on TF Cloud

on:
  workflow_dispatch:
    inputs:
      port_payload:
        required: true
        description: "Port's payload, including details for who triggered the action and general context (blueprint, run id, etc...)"
        type: string
    secrets: 
      PORT_CLIENT_ID: 
        required: true
      PORT_CLIENT_SECRET: 
        required: true
      TF_CLOUD_TOKEN: 
        required: true
      TF_CLOUD_TEAM_TOKEN: 
        required: true
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
       with:
         persist-credentials: true
         fetch-depth: 2
     - uses: actions/setup-python@v4
       with:
         python-version: '3.x'
     - name: echo fromJson(inputs.port_payload).properties
       run: echo ${{ fromJson(inputs.port_payload).properties }}
     - name: Run scanner script
       env:
         TF_CLOUD_TOKEN: ${{ secrets.TF_CLOUD_TOKEN }}
         TF_CLOUD_TEAM_TOKEN: ${{ secrets.TF_CLOUD_TEAM_TOKEN }}
         ORGANIATION_NAME: example-org-27d3a7
         ACTION_IDENTIFIER:  ${{ fromJson(inputs.port_payload).action.identifier }}
         VARIABLES: ${{ fromJson(inputs.port_payload).properties }}
         RUN_ID: ${{ fromJson(inputs.port_payload).context.runId }}
       run: |
           pip install -r .github/scripts/requirements.txt
           python .github/scripts/deploy-tf-module.py  