name: Sync port actions

on:
  workflow_dispatch:
    secrets: 
      PORT_CLIENT_ID: 
        required: true
      PORT_CLIENT_SECRET: 
        required: true
      TF_CLOUD_TOKEN: 
        required: true
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
       with:
         persist-credentials: true
         fetch-depth: 2
     - uses: actions/setup-python@v4
       with:
         python-version: '3.x'
     - name: Run scanner script
       env:
         TF_CLOUD_TOKEN: ${{ secrets.TF_CLOUD_TOKEN }}
         PORT_CLIENT_ID: ${{ secrets.PORT_CLIENT_ID }}
         PORT_CLIENT_SECRET: ${{ secrets.PORT_CLIENT_SECRET }}
         MODULES_TO_EXPORT: "[{\"module\": \"GoogleCloudPlatform/cloud-run/google\", \"versions\": [\"0.4.0\", \"0.3.0\"], \"examples\": [\"secure_cloud_run_standalone\", \"secure_cloud_run\", \"simple_cloud_run\"]}]"
         API_URL: https://api.getport.io/v1
       run: |
           pip install -r .github/scripts/requirements.txt
           python .github/scripts/port-tf-sync-actions.py  